# Generated by Django 6.0.3 on 2026-05-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_account_attempt_student_test_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='completion_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
