# Generated by Django 6.0.3 on 2026-05-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_attempt_completion_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='session_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
